// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -940558148;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_tradu_git',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiSimpleGitAdd({
    required String path,
    required String filePath,
  });

  Future<String> crateApiSimpleGitCheckoutBranch({
    required String path,
    required String branchName,
  });

  Future<String> crateApiSimpleGitClone({
    required String url,
    required String path,
  });

  Future<String> crateApiSimpleGitCommit({
    required String path,
    required String message,
    required String authorName,
    required String authorEmail,
  });

  Future<GitCompareInfo> crateApiSimpleGitCompareBranches({
    required String path,
    required String localBranch,
    required String remoteName,
  });

  Future<String> crateApiSimpleGitCreateBranch({
    required String path,
    required String branchName,
  });

  Future<String> crateApiSimpleGitCurrentBranch({required String path});

  Future<String> crateApiSimpleGitDiscardChanges({
    required String path,
    required String filePath,
  });

  Future<String> crateApiSimpleGitFetch({
    required String path,
    required String remoteName,
    required String branchName,
    String? username,
    String? password,
  });

  Future<List<String>> crateApiSimpleGitListBranches({required String path});

  Future<List<GitCommitInfo>> crateApiSimpleGitLog({
    required String path,
    required BigInt maxCount,
  });

  Future<String> crateApiSimpleGitPull({
    required String path,
    required String remoteName,
    required String branchName,
    String? username,
    String? password,
    String? authorName,
    String? authorEmail,
  });

  Future<String> crateApiSimpleGitPush({
    required String path,
    required String remoteName,
    required String branchName,
    String? username,
    String? password,
  });

  Future<String> crateApiSimpleGitReset({
    required String path,
    required String filePath,
  });

  Future<String> crateApiSimpleGitStatus({required String path});

  String crateApiSimpleGreet({required String name});

  bool crateApiSimpleHasGitRepo({required String path});

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiSimpleRunCommand({
    required String path,
    required String commandLine,
  });

  Future<String> crateApiSimpleSetupSslCertificates({required String filesDir});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiSimpleGitAdd({
    required String path,
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitAddConstMeta,
        argValues: [path, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitAddConstMeta =>
      const TaskConstMeta(debugName: "git_add", argNames: ["path", "filePath"]);

  @override
  Future<String> crateApiSimpleGitCheckoutBranch({
    required String path,
    required String branchName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(branchName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitCheckoutBranchConstMeta,
        argValues: [path, branchName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitCheckoutBranchConstMeta =>
      const TaskConstMeta(
        debugName: "git_checkout_branch",
        argNames: ["path", "branchName"],
      );

  @override
  Future<String> crateApiSimpleGitClone({
    required String url,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitCloneConstMeta,
        argValues: [url, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitCloneConstMeta =>
      const TaskConstMeta(debugName: "git_clone", argNames: ["url", "path"]);

  @override
  Future<String> crateApiSimpleGitCommit({
    required String path,
    required String message,
    required String authorName,
    required String authorEmail,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(message, serializer);
          sse_encode_String(authorName, serializer);
          sse_encode_String(authorEmail, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitCommitConstMeta,
        argValues: [path, message, authorName, authorEmail],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitCommitConstMeta => const TaskConstMeta(
    debugName: "git_commit",
    argNames: ["path", "message", "authorName", "authorEmail"],
  );

  @override
  Future<GitCompareInfo> crateApiSimpleGitCompareBranches({
    required String path,
    required String localBranch,
    required String remoteName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(localBranch, serializer);
          sse_encode_String(remoteName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_git_compare_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitCompareBranchesConstMeta,
        argValues: [path, localBranch, remoteName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitCompareBranchesConstMeta =>
      const TaskConstMeta(
        debugName: "git_compare_branches",
        argNames: ["path", "localBranch", "remoteName"],
      );

  @override
  Future<String> crateApiSimpleGitCreateBranch({
    required String path,
    required String branchName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(branchName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitCreateBranchConstMeta,
        argValues: [path, branchName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitCreateBranchConstMeta =>
      const TaskConstMeta(
        debugName: "git_create_branch",
        argNames: ["path", "branchName"],
      );

  @override
  Future<String> crateApiSimpleGitCurrentBranch({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitCurrentBranchConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitCurrentBranchConstMeta =>
      const TaskConstMeta(debugName: "git_current_branch", argNames: ["path"]);

  @override
  Future<String> crateApiSimpleGitDiscardChanges({
    required String path,
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitDiscardChangesConstMeta,
        argValues: [path, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitDiscardChangesConstMeta =>
      const TaskConstMeta(
        debugName: "git_discard_changes",
        argNames: ["path", "filePath"],
      );

  @override
  Future<String> crateApiSimpleGitFetch({
    required String path,
    required String remoteName,
    required String branchName,
    String? username,
    String? password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(remoteName, serializer);
          sse_encode_String(branchName, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitFetchConstMeta,
        argValues: [path, remoteName, branchName, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitFetchConstMeta => const TaskConstMeta(
    debugName: "git_fetch",
    argNames: ["path", "remoteName", "branchName", "username", "password"],
  );

  @override
  Future<List<String>> crateApiSimpleGitListBranches({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitListBranchesConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitListBranchesConstMeta =>
      const TaskConstMeta(debugName: "git_list_branches", argNames: ["path"]);

  @override
  Future<List<GitCommitInfo>> crateApiSimpleGitLog({
    required String path,
    required BigInt maxCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_usize(maxCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_git_commit_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitLogConstMeta,
        argValues: [path, maxCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitLogConstMeta =>
      const TaskConstMeta(debugName: "git_log", argNames: ["path", "maxCount"]);

  @override
  Future<String> crateApiSimpleGitPull({
    required String path,
    required String remoteName,
    required String branchName,
    String? username,
    String? password,
    String? authorName,
    String? authorEmail,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(remoteName, serializer);
          sse_encode_String(branchName, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          sse_encode_opt_String(authorName, serializer);
          sse_encode_opt_String(authorEmail, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitPullConstMeta,
        argValues: [
          path,
          remoteName,
          branchName,
          username,
          password,
          authorName,
          authorEmail,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitPullConstMeta => const TaskConstMeta(
    debugName: "git_pull",
    argNames: [
      "path",
      "remoteName",
      "branchName",
      "username",
      "password",
      "authorName",
      "authorEmail",
    ],
  );

  @override
  Future<String> crateApiSimpleGitPush({
    required String path,
    required String remoteName,
    required String branchName,
    String? username,
    String? password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(remoteName, serializer);
          sse_encode_String(branchName, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitPushConstMeta,
        argValues: [path, remoteName, branchName, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitPushConstMeta => const TaskConstMeta(
    debugName: "git_push",
    argNames: ["path", "remoteName", "branchName", "username", "password"],
  );

  @override
  Future<String> crateApiSimpleGitReset({
    required String path,
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitResetConstMeta,
        argValues: [path, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitResetConstMeta => const TaskConstMeta(
    debugName: "git_reset",
    argNames: ["path", "filePath"],
  );

  @override
  Future<String> crateApiSimpleGitStatus({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGitStatusConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGitStatusConstMeta =>
      const TaskConstMeta(debugName: "git_status", argNames: ["path"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  bool crateApiSimpleHasGitRepo({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleHasGitRepoConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleHasGitRepoConstMeta =>
      const TaskConstMeta(debugName: "has_git_repo", argNames: ["path"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiSimpleRunCommand({
    required String path,
    required String commandLine,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(commandLine, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleRunCommandConstMeta,
        argValues: [path, commandLine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRunCommandConstMeta => const TaskConstMeta(
    debugName: "run_command",
    argNames: ["path", "commandLine"],
  );

  @override
  Future<String> crateApiSimpleSetupSslCertificates({
    required String filesDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filesDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSetupSslCertificatesConstMeta,
        argValues: [filesDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetupSslCertificatesConstMeta =>
      const TaskConstMeta(
        debugName: "setup_ssl_certificates",
        argNames: ["filesDir"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  GitCommitInfo dco_decode_git_commit_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return GitCommitInfo(
      hash: dco_decode_String(arr[0]),
      author: dco_decode_String(arr[1]),
      email: dco_decode_String(arr[2]),
      time: dco_decode_i_64(arr[3]),
      message: dco_decode_String(arr[4]),
    );
  }

  @protected
  GitCompareInfo dco_decode_git_compare_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GitCompareInfo(
      ahead: dco_decode_usize(arr[0]),
      behind: dco_decode_usize(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<GitCommitInfo> dco_decode_list_git_commit_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_git_commit_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  GitCommitInfo sse_decode_git_commit_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hash = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    var var_time = sse_decode_i_64(deserializer);
    var var_message = sse_decode_String(deserializer);
    return GitCommitInfo(
      hash: var_hash,
      author: var_author,
      email: var_email,
      time: var_time,
      message: var_message,
    );
  }

  @protected
  GitCompareInfo sse_decode_git_compare_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ahead = sse_decode_usize(deserializer);
    var var_behind = sse_decode_usize(deserializer);
    return GitCompareInfo(ahead: var_ahead, behind: var_behind);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<GitCommitInfo> sse_decode_list_git_commit_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GitCommitInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_git_commit_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_git_commit_info(
    GitCommitInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hash, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.email, serializer);
    sse_encode_i_64(self.time, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_git_compare_info(
    GitCompareInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.ahead, serializer);
    sse_encode_usize(self.behind, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_git_commit_info(
    List<GitCommitInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_git_commit_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
